<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Version>0.1.0-dev</Version>
    <PackageId>TinySuite.TinyBus</PackageId>
    <Description>Compile-time-oriented messaging contracts for TinyBus.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.10" />
    <InternalsVisibleTo Include="TinyBus.PostgreSql.Tests" />
    <InternalsVisibleTo Include="TinyBus.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../TinyBus.SourceGen/TinyBus.SourceGen.csproj"
                      ReferenceOutputAssembly="false"
                      PrivateAssets="all" />
    <None Include="../TinyBus.SourceGen/bin/$(Configuration)/netstandard2.0/TinyBus.SourceGen.dll"
          Pack="true"
          PackagePath="analyzers/dotnet/cs"
          Visible="false" />
    <None Include="../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
