<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Version>0.1.0-dev</Version>
    <PackageId>TinySuite.TinyBus</PackageId>
    <Description>Compile-time-oriented messaging contracts for TinyBus.</Description>
  </PropertyGroup>
</Project>
