using System.Threading;
using TinyBus.SourceGen.Generation.Planning;
using TinyBus.SourceGen.Model;

namespace TinyBus.SourceGen.Generation.Emission;

internal sealed class IncomingPipelineEmitter
{
    public string Emit(
        IncomingPipelinePlan plan,
        CancellationToken cancellationToken)
    {
        var writer = new SourceWriter();

        WriteHeader(writer);
        writer.WriteLine("namespace TinyBus.Generated");
        writer.WriteLine("{");
        writer.Indent();

        WriteLocalCommandExecution(writer, plan, cancellationToken);
        writer.WriteLine();
        WriteIncomingPipeline(writer, plan, cancellationToken);

        writer.Unindent();
        writer.WriteLine("}");

        return writer.ToString();
    }

    private static void WriteHeader(SourceWriter writer)
    {
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
    }

    private static void WriteLocalCommandExecution(
        SourceWriter writer,
        IncomingPipelinePlan plan,
        CancellationToken cancellationToken)
    {
        writer.WriteLine($"public sealed partial class {plan.LocalManifestTypeName}");
        writer.WriteLine("{");
        writer.Indent();

        WriteCommandEntryPoint(writer, plan, cancellationToken);

        for (var index = 0; index < plan.LocalCommands.Length; index++)
        {
            cancellationToken.ThrowIfCancellationRequested();
            writer.WriteLine();
            WriteCommandExecution(writer, plan.LocalCommands[index], index);
        }

        writer.Unindent();
        writer.WriteLine("}");
    }

    private static void WriteCommandEntryPoint(
        SourceWriter writer,
        IncomingPipelinePlan plan,
        CancellationToken cancellationToken)
    {
        writer.WriteLine("public static global::System.Threading.Tasks.ValueTask ExecuteCommandAsync(");
        writer.Indent();
        writer.WriteLine("global::System.IServiceProvider services,");
        writer.WriteLine("global::TinyBus.MessageEnvelope message,");
        writer.WriteLine("global::System.Threading.CancellationToken cancellationToken)");
        writer.Unindent();
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("global::System.ArgumentNullException.ThrowIfNull(services);");
        writer.WriteLine("global::System.ArgumentNullException.ThrowIfNull(message);");

        for (var index = 0; index < plan.LocalCommands.Length; index++)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var command = plan.LocalCommands[index];
            var contractName = FormatStringLiteral(command.ContractName);

            writer.WriteLine();
            writer.WriteLine($"var commandContract{index} = new global::TinyBus.ContractIdentity({contractName}, {command.ContractVersion});");
            writer.WriteLine($"if (message.Contract == commandContract{index})");
            writer.WriteLine("{");
            writer.Indent();
            writer.WriteLine($"var execution = ExecuteCommand{index}Async(services, message, cancellationToken);");
            writer.WriteLine("return execution;");
            writer.Unindent();
            writer.WriteLine("}");
        }

        writer.WriteLine();
        WriteUnknownCommand(writer);
        writer.Unindent();
        writer.WriteLine("}");
    }

    private static void WriteCommandExecution(
        SourceWriter writer,
        MessageHandlerDefinition command,
        int index)
    {
        writer.WriteLine($"private static global::System.Threading.Tasks.ValueTask ExecuteCommand{index}Async(");
        writer.Indent();
        writer.WriteLine("global::System.IServiceProvider services,");
        writer.WriteLine("global::TinyBus.MessageEnvelope message,");
        writer.WriteLine("global::System.Threading.CancellationToken cancellationToken)");
        writer.Unindent();
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine($"var command = global::System.Text.Json.JsonSerializer.Deserialize<{command.MessageTypeName}>(message.Payload);");
        writer.WriteLine("if (command is null)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("throw new global::System.InvalidOperationException(\"The command payload produced a null message.\");");
        writer.Unindent();
        writer.WriteLine("}");
        writer.WriteLine();
        writer.WriteLine("var executor = new global::TinyBus.CommandExecutor(services);");
        writer.WriteLine("var execution = executor.ExecuteAsync(command, cancellationToken);");
        writer.WriteLine();
        writer.WriteLine("return execution;");
        writer.Unindent();
        writer.WriteLine("}");
    }

    private static void WriteIncomingPipeline(
        SourceWriter writer,
        IncomingPipelinePlan plan,
        CancellationToken cancellationToken)
    {
        writer.WriteLine("internal sealed class GeneratedIncomingMessagePipeline : global::TinyBus.IIncomingMessagePipeline");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("private readonly global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory scopeFactory;");
        writer.WriteLine();
        WritePipelineConstructor(writer);
        writer.WriteLine();
        WritePipelineExecution(writer);
        writer.WriteLine();
        WriteCommandDispatch(writer, plan, cancellationToken);
        writer.Unindent();
        writer.WriteLine("}");
    }

    private static void WritePipelineConstructor(SourceWriter writer)
    {
        writer.WriteLine("public GeneratedIncomingMessagePipeline(");
        writer.Indent();
        writer.WriteLine("global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory scopeFactory)");
        writer.Unindent();
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("global::System.ArgumentNullException.ThrowIfNull(scopeFactory);");
        writer.WriteLine("this.scopeFactory = scopeFactory;");
        writer.Unindent();
        writer.WriteLine("}");
    }

    private static void WritePipelineExecution(SourceWriter writer)
    {
        writer.WriteLine("public async global::System.Threading.Tasks.ValueTask ExecuteAsync(");
        writer.Indent();
        writer.WriteLine("global::TinyBus.MessageEnvelope message,");
        writer.WriteLine("global::System.Threading.CancellationToken cancellationToken = default)");
        writer.Unindent();
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("global::System.ArgumentNullException.ThrowIfNull(message);");
        writer.WriteLine();
        writer.WriteLine("await using var scope = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.CreateAsyncScope(scopeFactory);");
        writer.WriteLine("var services = scope.ServiceProvider;");
        writer.WriteLine("var execution = DispatchCommandAsync(services, message, cancellationToken);");
        writer.WriteLine();
        writer.WriteLine("await execution.ConfigureAwait(false);");
        writer.Unindent();
        writer.WriteLine("}");
    }

    private static void WriteCommandDispatch(
        SourceWriter writer,
        IncomingPipelinePlan plan,
        CancellationToken cancellationToken)
    {
        writer.WriteLine("private static global::System.Threading.Tasks.ValueTask DispatchCommandAsync(");
        writer.Indent();
        writer.WriteLine("global::System.IServiceProvider services,");
        writer.WriteLine("global::TinyBus.MessageEnvelope message,");
        writer.WriteLine("global::System.Threading.CancellationToken cancellationToken)");
        writer.Unindent();
        writer.WriteLine("{");
        writer.Indent();

        for (var index = 0; index < plan.CommandTargets.Length; index++)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var target = plan.CommandTargets[index];
            var contractName = FormatStringLiteral(target.ContractName);

            writer.WriteLine($"var commandContract{index} = new global::TinyBus.ContractIdentity({contractName}, {target.ContractVersion});");
            writer.WriteLine($"if (message.Contract == commandContract{index})");
            writer.WriteLine("{");
            writer.Indent();
            writer.WriteLine($"var execution = {target.ManifestTypeName}.ExecuteCommandAsync(services, message, cancellationToken);");
            writer.WriteLine("return execution;");
            writer.Unindent();
            writer.WriteLine("}");
            writer.WriteLine();
        }

        WriteUnknownCommand(writer);
        writer.Unindent();
        writer.WriteLine("}");
    }

    private static void WriteUnknownCommand(SourceWriter writer)
    {
        writer.WriteLine("var contract = message.Contract;");
        writer.WriteLine("var error = $\"No command handler is registered for '{contract.Name}' version {contract.Version}.\";");
        writer.WriteLine("throw new global::System.InvalidOperationException(error);");
    }

    private static string FormatStringLiteral(string value)
    {
        var escaped = value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\0", "\\0")
            .Replace("\a", "\\a")
            .Replace("\b", "\\b")
            .Replace("\f", "\\f")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t")
            .Replace("\v", "\\v")
            .Replace("\u0085", "\\u0085")
            .Replace("\u2028", "\\u2028")
            .Replace("\u2029", "\\u2029");

        return $"\"{escaped}\"";
    }
}
