using System.Text;
using System.Threading;
using TinyBus.SourceGen.Generation.Planning;
using TinyBus.SourceGen.Model;

namespace TinyBus.SourceGen.Generation.Emission;

internal sealed class ManifestEmitter
{
    public string Emit(ManifestPlan plan, CancellationToken cancellationToken)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine("namespace TinyBus.Generated");
        source.AppendLine("{");
        source.AppendLine("    internal sealed class GeneratedTinyBusManifest : global::TinyBus.IBusManifest");
        source.AppendLine("    {");
        source.AppendLine("        public global::System.Collections.Generic.IReadOnlyList<global::TinyBus.MessageDescriptor> Messages { get; } =");
        source.AppendLine("            global::System.Array.AsReadOnly(new global::TinyBus.MessageDescriptor[]");
        source.AppendLine("            {");

        foreach (var message in plan.Messages)
        {
            cancellationToken.ThrowIfCancellationRequested();
            WriteMessage(source, message);
        }

        source.AppendLine("            });");
        source.AppendLine("    }");
        source.AppendLine("}");
        return source.ToString();
    }

    private static void WriteMessage(StringBuilder source, MessageHandlerDefinition message)
    {
        source.AppendLine("                new global::TinyBus.MessageDescriptor(");
        source.Append("                    new global::TinyBus.ContractIdentity(");
        WriteString(source, message.ContractName);
        source.AppendLine(", 1),");
        source.Append("                    typeof(").Append(message.MessageTypeName).AppendLine("),");
        source.Append("                    typeof(").Append(message.HandlerTypeName).AppendLine("),");
        source.Append("                    global::TinyBus.MessageKind.").Append(message.Kind);

        if (message.ResponseTypeName is null)
        {
            source.AppendLine("),");
            return;
        }

        source.AppendLine(",");
        source.Append("                    typeof(").Append(message.ResponseTypeName).AppendLine(")),");
    }

    private static void WriteString(StringBuilder source, string value)
    {
        source.Append('"');
        foreach (var character in value)
        {
            switch (character)
            {
                case '\\':
                    source.Append("\\\\");
                    break;
                case '"':
                    source.Append("\\\"");
                    break;
                default:
                    source.Append(character);
                    break;
            }
        }

        source.Append('"');
    }
}
