using System;
using System.Threading;
using TinyBus.SourceGen.Generation.Planning;
using TinyBus.SourceGen.Model;

namespace TinyBus.SourceGen.Generation.Emission;

internal sealed class ManifestEmitter
{
    public string Emit(ManifestPlan plan, CancellationToken cancellationToken)
    {
        var writer = new SourceWriter();

        WriteHeader(writer);
        WriteContributions(writer, plan, cancellationToken);

        writer.WriteLine("namespace TinyBus.Generated");
        writer.WriteLine("{");
        writer.Indent();

        WriteLocalManifest(writer, plan, cancellationToken);
        writer.WriteLine();
        WriteComposedManifest(writer, plan, cancellationToken);

        writer.Unindent();
        writer.WriteLine("}");

        writer.WriteLine();
        WriteApplicationRegistration(writer);

        return writer.ToString();
    }

    private static void WriteApplicationRegistration(SourceWriter writer)
    {
        writer.WriteLine("namespace TinyBus");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("internal static class GeneratedTinyBusServiceCollectionExtensions");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddTinyBus(");
        writer.Indent();
        writer.WriteLine("this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,");
        writer.WriteLine("global::System.Action<global::TinyBus.TinyBusOptions> configure)");
        writer.Unindent();
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("global::TinyBus.TinyBusServiceCollectionExtensions.AddTinyBus<global::TinyBus.Generated.GeneratedTinyBusManifest>(services, configure);");
        writer.WriteLine();
        writer.WriteLine("global::TinyBus.Generated.GeneratedTinyBusManifest.RegisterHandlers(services);");
        writer.WriteLine();
        writer.WriteLine("return services;");
        writer.Unindent();
        writer.WriteLine("}");
        writer.Unindent();
        writer.WriteLine("}");
        writer.Unindent();
        writer.WriteLine("}");
    }

    private static void WriteHeader(SourceWriter writer)
    {
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
    }

    private static void WriteContributions(
        SourceWriter writer,
        ManifestPlan plan,
        CancellationToken cancellationToken)
    {
        foreach (var message in plan.Messages)
        {
            cancellationToken.ThrowIfCancellationRequested();
            WriteContribution(writer, plan.ManifestTypeName, message);
        }

        writer.WriteLine();
    }

    private static void WriteContribution(
        SourceWriter writer,
        string manifestTypeName,
        MessageHandlerDefinition message)
    {
        var contractName = FormatStringLiteral(message.ContractName);
        var responseType = FormatResponseType(message);

        writer.WriteLine("[assembly: global::TinyBus.BusMessageContributionAttribute(");
        writer.Indent();
        writer.WriteLine($"typeof(global::TinyBus.Generated.{manifestTypeName}),");
        writer.WriteLine($"{contractName}, {message.ContractVersion},");
        writer.WriteLine($"typeof({message.MessageTypeName}),");
        writer.WriteLine($"typeof({message.HandlerTypeName}),");
        writer.WriteLine($"global::TinyBus.MessageKind.{message.Kind},");
        writer.WriteLine($"{responseType})]");
        writer.Unindent();
    }

    private static void WriteLocalManifest(
        SourceWriter writer,
        ManifestPlan plan,
        CancellationToken cancellationToken)
    {
        writer.WriteLine($"public sealed class {plan.ManifestTypeName} : global::TinyBus.IBusManifest");
        writer.WriteLine("{");
        writer.Indent();

        writer.WriteLine("public global::System.Collections.Generic.IReadOnlyList<global::TinyBus.MessageDescriptor> Messages { get; } = CreateMessages();");
        writer.WriteLine();

        WriteLocalHandlerRegistration(writer, plan, cancellationToken);
        writer.WriteLine();
        WriteMessageCreation(writer, plan, cancellationToken);

        writer.Unindent();
        writer.WriteLine("}");
    }

    private static void WriteLocalHandlerRegistration(
        SourceWriter writer,
        ManifestPlan plan,
        CancellationToken cancellationToken)
    {
        writer.WriteLine("public static void RegisterLocalHandlers(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("global::System.ArgumentNullException.ThrowIfNull(services);");

        for (var index = 0; index < plan.Messages.Length; index++)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var message = plan.Messages[index];

            writer.WriteLine();
            WriteHandlerRegistration(writer, message, index);
        }

        writer.Unindent();
        writer.WriteLine("}");
    }

    private static void WriteHandlerRegistration(
        SourceWriter writer,
        MessageHandlerDefinition message,
        int index)
    {
        var handlerInterface = FormatHandlerInterface(message);

        writer.WriteLine($"var handlerRegistration{index} = global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Scoped(");
        writer.Indent();
        writer.WriteLine($"typeof({handlerInterface}),");
        writer.WriteLine($"typeof({message.HandlerTypeName}));");
        writer.Unindent();

        writer.WriteLine($"global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(services, handlerRegistration{index});");
    }

    private static void WriteMessageCreation(
        SourceWriter writer,
        ManifestPlan plan,
        CancellationToken cancellationToken)
    {
        writer.WriteLine("private static global::System.Collections.Generic.IReadOnlyList<global::TinyBus.MessageDescriptor> CreateMessages()");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine($"var messages = new global::TinyBus.MessageDescriptor[{plan.Messages.Length}];");

        for (var index = 0; index < plan.Messages.Length; index++)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var message = plan.Messages[index];

            writer.WriteLine();
            WriteMessage(writer, message, index);
        }

        writer.WriteLine();
        writer.WriteLine("return global::System.Array.AsReadOnly(messages);");
        writer.Unindent();
        writer.WriteLine("}");
    }

    private static void WriteMessage(
        SourceWriter writer,
        MessageHandlerDefinition message,
        int index)
    {
        var contractName = FormatStringLiteral(message.ContractName);
        var responseType = FormatResponseType(message);

        writer.WriteLine($"var contract{index} = new global::TinyBus.ContractIdentity({contractName}, {message.ContractVersion});");
        writer.WriteLine($"var message{index} = new global::TinyBus.MessageDescriptor(");
        writer.Indent();
        writer.WriteLine($"contract{index},");
        writer.WriteLine($"typeof({message.MessageTypeName}),");
        writer.WriteLine($"typeof({message.HandlerTypeName}),");
        writer.WriteLine($"global::TinyBus.MessageKind.{message.Kind},");
        writer.WriteLine($"{responseType});");
        writer.Unindent();
        writer.WriteLine($"messages[{index}] = message{index};");
    }

    private static void WriteComposedManifest(
        SourceWriter writer,
        ManifestPlan plan,
        CancellationToken cancellationToken)
    {
        writer.WriteLine("internal sealed class GeneratedTinyBusManifest : global::TinyBus.IBusManifest");
        writer.WriteLine("{");
        writer.Indent();

        writer.WriteLine("public global::System.Collections.Generic.IReadOnlyList<global::TinyBus.MessageDescriptor> Messages { get; } = ComposeMessages();");
        writer.WriteLine();

        WriteTopologyCreation(writer);
        writer.WriteLine();
        WriteComposedHandlerRegistration(writer, plan, cancellationToken);
        writer.WriteLine();
        WriteMessageComposition(writer, plan, cancellationToken);

        writer.Unindent();
        writer.WriteLine("}");
    }

    private static void WriteTopologyCreation(SourceWriter writer)
    {
        writer.WriteLine("public global::TinyBus.ServiceTopology CreateTopology(global::TinyBus.ServiceIdentity service)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("return new global::TinyBus.ServiceTopology(service, Messages);");
        writer.Unindent();
        writer.WriteLine("}");
    }

    private static void WriteComposedHandlerRegistration(
        SourceWriter writer,
        ManifestPlan plan,
        CancellationToken cancellationToken)
    {
        writer.WriteLine("public static void RegisterHandlers(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("global::System.ArgumentNullException.ThrowIfNull(services);");
        writer.WriteLine($"{plan.ManifestTypeName}.RegisterLocalHandlers(services);");

        foreach (var manifestTypeName in plan.ReferencedManifestTypeNames)
        {
            cancellationToken.ThrowIfCancellationRequested();
            writer.WriteLine($"{manifestTypeName}.RegisterLocalHandlers(services);");
        }

        writer.Unindent();
        writer.WriteLine("}");
    }

    private static void WriteMessageComposition(
        SourceWriter writer,
        ManifestPlan plan,
        CancellationToken cancellationToken)
    {
        writer.WriteLine("private static global::System.Collections.Generic.IReadOnlyList<global::TinyBus.MessageDescriptor> ComposeMessages()");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("var messages = new global::System.Collections.Generic.List<global::TinyBus.MessageDescriptor>();");
        writer.WriteLine($"var localManifest = new {plan.ManifestTypeName}();");
        writer.WriteLine("messages.AddRange(localManifest.Messages);");

        for (var index = 0; index < plan.ReferencedManifestTypeNames.Length; index++)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var manifestTypeName = plan.ReferencedManifestTypeNames[index];

            writer.WriteLine();
            writer.WriteLine($"var referencedManifest{index} = new {manifestTypeName}();");
            writer.WriteLine($"messages.AddRange(referencedManifest{index}.Messages);");
        }

        writer.WriteLine();
        writer.WriteLine("return messages.AsReadOnly();");
        writer.Unindent();
        writer.WriteLine("}");
    }

    private static string FormatHandlerInterface(MessageHandlerDefinition message)
    {
        return message.Kind switch
        {
            MessageHandlerKind.Command => $"global::TinyBus.ICommandHandler<{message.MessageTypeName}>",
            MessageHandlerKind.Event => $"global::TinyBus.IEventHandler<{message.MessageTypeName}>",
            MessageHandlerKind.Request => $"global::TinyBus.IRequestHandler<{message.MessageTypeName}, {message.ResponseTypeName}>",
            _ => throw new InvalidOperationException("Unsupported handler kind.")
        };
    }

    private static string FormatResponseType(MessageHandlerDefinition message)
    {
        return message.ResponseTypeName is null
            ? "null"
            : $"typeof({message.ResponseTypeName})";
    }

    private static string FormatStringLiteral(string value)
    {
        var escaped = value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\0", "\\0")
            .Replace("\a", "\\a")
            .Replace("\b", "\\b")
            .Replace("\f", "\\f")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t")
            .Replace("\v", "\\v")
            .Replace("\u0085", "\\u0085")
            .Replace("\u2028", "\\u2028")
            .Replace("\u2029", "\\u2029");

        return $"\"{escaped}\"";
    }
}
