using System.Text;
using System.Threading;
using TinyBus.SourceGen.Generation.Planning;
using TinyBus.SourceGen.Model;

namespace TinyBus.SourceGen.Generation.Emission;

internal sealed class ManifestEmitter
{
    public string Emit(ManifestPlan plan, CancellationToken cancellationToken)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();

        WriteContributions(source, plan, cancellationToken);
        WriteManifest(source, plan, cancellationToken);

        return source.ToString();
    }

    private static void WriteContributions(
        StringBuilder source,
        ManifestPlan plan,
        CancellationToken cancellationToken)
    {
        foreach (var message in plan.Messages)
        {
            cancellationToken.ThrowIfCancellationRequested();
            WriteContribution(source, plan.ManifestTypeName, message);
        }

        if (plan.Messages.Length > 0)
        {
            source.AppendLine();
        }
    }

    private static void WriteContribution(
        StringBuilder source,
        string manifestTypeName,
        MessageHandlerDefinition message)
    {
        source.AppendLine("[assembly: global::TinyBus.BusMessageContributionAttribute(");
        source.Append("    typeof(global::TinyBus.Generated.").Append(manifestTypeName).AppendLine("),");
        source.Append("    ");
        WriteString(source, message.ContractName);
        source.Append(", ").Append(message.ContractVersion).AppendLine(",");
        source.Append("    typeof(").Append(message.MessageTypeName).AppendLine("),");
        source.Append("    typeof(").Append(message.HandlerTypeName).AppendLine("),");
        source.Append("    global::TinyBus.MessageKind.").Append(message.Kind);

        if (message.ResponseTypeName is not null)
        {
            source.AppendLine(",");
            source.Append("    typeof(").Append(message.ResponseTypeName).Append(')');
        }

        source.AppendLine(")]");
    }

    private static void WriteManifest(
        StringBuilder source,
        ManifestPlan plan,
        CancellationToken cancellationToken)
    {
        source.AppendLine("namespace TinyBus.Generated");
        source.AppendLine("{");

        WriteLocalManifest(source, plan, cancellationToken);
        source.AppendLine();
        WriteComposedManifest(source, plan, cancellationToken);

        source.AppendLine("}");
    }

    private static void WriteLocalManifest(
        StringBuilder source,
        ManifestPlan plan,
        CancellationToken cancellationToken)
    {
        source.Append("    public sealed class ").Append(plan.ManifestTypeName)
            .AppendLine(" : global::TinyBus.IBusManifest");
        source.AppendLine("    {");
        source.AppendLine("        public global::System.Collections.Generic.IReadOnlyList<global::TinyBus.MessageDescriptor> Messages { get; } =");
        source.AppendLine("            global::System.Array.AsReadOnly(new global::TinyBus.MessageDescriptor[]");
        source.AppendLine("            {");

        foreach (var message in plan.Messages)
        {
            cancellationToken.ThrowIfCancellationRequested();
            WriteMessage(source, message);
        }

        source.AppendLine("            });");
        source.AppendLine("    }");
    }

    private static void WriteComposedManifest(
        StringBuilder source,
        ManifestPlan plan,
        CancellationToken cancellationToken)
    {
        source.AppendLine("    internal sealed class GeneratedTinyBusManifest : global::TinyBus.IBusManifest");
        source.AppendLine("    {");
        source.AppendLine("        public global::System.Collections.Generic.IReadOnlyList<global::TinyBus.MessageDescriptor> Messages { get; } = ComposeMessages();");
        source.AppendLine();
        source.AppendLine("        private static global::System.Collections.Generic.IReadOnlyList<global::TinyBus.MessageDescriptor> ComposeMessages()");
        source.AppendLine("        {");
        source.AppendLine("            var messages = new global::System.Collections.Generic.List<global::TinyBus.MessageDescriptor>();");
        source.Append("            messages.AddRange(new ").Append(plan.ManifestTypeName).AppendLine("().Messages);");

        // Referenced manifests expose their own descriptors, including assembly-internal types.
        foreach (var manifestTypeName in plan.ReferencedManifestTypeNames)
        {
            cancellationToken.ThrowIfCancellationRequested();
            source.Append("            messages.AddRange(new ").Append(manifestTypeName).AppendLine("().Messages);");
        }

        source.AppendLine();
        source.AppendLine("            return messages.AsReadOnly();");
        source.AppendLine("        }");
        source.AppendLine("    }");
    }

    private static void WriteMessage(StringBuilder source, MessageHandlerDefinition message)
    {
        source.AppendLine("                new global::TinyBus.MessageDescriptor(");
        source.Append("                    new global::TinyBus.ContractIdentity(");
        WriteString(source, message.ContractName);
        source.Append(", ").Append(message.ContractVersion).AppendLine("),");
        source.Append("                    typeof(").Append(message.MessageTypeName).AppendLine("),");
        source.Append("                    typeof(").Append(message.HandlerTypeName).AppendLine("),");
        source.Append("                    global::TinyBus.MessageKind.").Append(message.Kind);

        if (message.ResponseTypeName is null)
        {
            source.AppendLine("),");
            return;
        }

        source.AppendLine(",");
        source.Append("                    typeof(").Append(message.ResponseTypeName).AppendLine(")),");
    }

    private static void WriteString(StringBuilder source, string value)
    {
        source.Append('"');
        foreach (var character in value)
        {
            switch (character)
            {
                case '\\':
                    source.Append("\\\\");
                    break;
                case '"':
                    source.Append("\\\"");
                    break;
                case '\0':
                    source.Append("\\0");
                    break;
                case '\a':
                    source.Append("\\a");
                    break;
                case '\b':
                    source.Append("\\b");
                    break;
                case '\f':
                    source.Append("\\f");
                    break;
                case '\n':
                    source.Append("\\n");
                    break;
                case '\r':
                    source.Append("\\r");
                    break;
                case '\t':
                    source.Append("\\t");
                    break;
                case '\v':
                    source.Append("\\v");
                    break;
                default:
                    source.Append(character);
                    break;
            }
        }

        source.Append('"');
    }
}
